2022-11-18 16:26:11.8328 INFO Getting product details by product id
2022-11-18 16:26:59.1043 INFO Getting product details by product id
2022-11-18 16:27:01.6797 INFO Getting product details by product id
2022-11-18 16:27:21.1761 INFO Getting product details by product id
2022-11-18 16:27:25.0576 ERROR Exception occured AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
Product -> ProductResponse
ProductsDemo.Data.DataAccess.Product -> ProductsDemo.Model.ProductResponse

Type Map configuration:
Product -> ProductResponse
ProductsDemo.Data.DataAccess.Product -> ProductsDemo.Model.ProductResponse

Destination Member:
Articles

 ---> AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.

Mapping types:
Article -> Article
ProductsDemo.Data.DataAccess.Article -> ProductsDemo.Model.Article
   at lambda_method108(Closure , Article , Article , ResolutionContext )
   at lambda_method107(Closure , Object , ProductResponse , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method107(Closure , Object , ProductResponse , ResolutionContext )
   at ProductsDemo.Service.ProductsService.GetProductById(Guid productId) in C:\Users\skandhasamy\Documents\Suganya\ProductsDemo\ProductsDemo\ProductsDemo.Service\ProductsService.cs:line 25
   at ProductsDemo.Api.Controllers.ProductsController.GetProductById(Guid productId) in C:\Users\skandhasamy\Documents\Suganya\ProductsDemo\ProductsDemo\ProductsDemo.Api\Controllers\ProductsController.cs:line 40
2022-11-18 16:38:56.0861 INFO Getting product details by product id
2022-11-18 16:39:36.2807 INFO Creating product
2022-11-18 16:39:41.5526 ERROR Exception occured System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it. (localhost:7022))
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:7022)
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at ProductsDemo.Api.Controllers.ProductsController.CallColorCodeApi() in C:\Users\skandhasamy\Documents\Suganya\ProductsDemo\ProductsDemo\ProductsDemo.Api\Controllers\ProductsController.cs:line 101
   at ProductsDemo.Api.Controllers.ProductsController.CreateProductAsync(ProductRequest product) in C:\Users\skandhasamy\Documents\Suganya\ProductsDemo\ProductsDemo\ProductsDemo.Api\Controllers\ProductsController.cs:line 75
2022-11-18 16:41:35.3050 INFO Getting product details by product id
2022-11-18 16:42:25.0244 INFO Getting product details by product id
